### ISSUE TITLE
VSCode language support doesn't work for embeded tags

### ISSUE THREAD

**Issue by LiuJi-Jim** [LiuJi-Jim/vscode-vue#12]
VSCode (seems) doesn't activate full-featured language support for embedded tags.
That means JavaScript Intellisense and HTML Emmet doesn't work in `.vue` Files.

I found that even if writing embedded `<script>` tags in `.html` file, JavaScript Intellisense doesn't work either. What a pity...

Still trying to solve this problem.

**Comment by externuz** [comment]
<style lang="stylus"> in .vue files
^ indent does not work, syntax highlight is not valid

**Comment by youanden** [comment]
Take a look at this issue: 
https://github.com/Microsoft/vscode/issues/9500

They seem to be working on this now. @egamma seems to have acknowledged @mrmlnc's similar use case.

**Comment by mrmlnc** [comment]
This question is not entirely belongs to 9500.

Yes, in the current Insiders builds Emmet will work with this extension.

But this issue refers to the support for nested (embedded) languages. See #8938 and #8928.

**Comment by frankdugan3** [comment]
With the 1.7 release, it seems as though all of the blocking VSCode issues have been addressed. Is it now possible to fix this issue?

**Comment by LiuJi-Jim** [comment]
@frankdugan3 
As currently tested, ES2015 syntax highlighting in `.vue` files is now working. but JavaScript Intellisense it still not.
Probably I will merge the `tmLanguage` file from [vuejs/vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight) in this week.

**Comment by frankdugan3** [comment]
@LiuJi-Jim The VSCode release today finally added Javascript Intellisense to HTML/embedded files, and they also added support for the rest/spread operator.
