### ISSUE TITLE
syntax not highlighting on <template>

### ISSUE THREAD

**Issue by jcpst** [LiuJi-Jim/vscode-vue#17]
Great plugin, thank you for making it. However, I'm not seeing any syntax highlighting on any jade/pug templates.

**VSCode version:** 1.4
**vscode-vue version:** 0.1.3
**Platform:** Linux arch 4.7.0-1-ARCH x86_64 GNU/Linux

![no-highlight-jade](https://cloud.githubusercontent.com/assets/4027669/17749514/9d3a095e-6483-11e6-9fb3-4c6ff0465802.png)

**Comment by hemulin** [comment]
Same here.
**VSCode version**: 1.6
**vscode-vue version**: 0.1.3
**Platform**: lubuntu 16.04 4.7.3-040703-generic x86_64 GNU/Linux

**Comment by LiuJi-Jim** [comment]
fixed in 0.1.4
P.S. VSCode doesn't defaultly support stylus, you may need to install a stylus extension. vscode-vue is tested to work with [sysoev/language-stylus](https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus).

**Comment by jakepeyser** [comment]
The best Vue support I can find for VScode, but still not seeing Pug syntax highlighting:

```pug
<template lang="pug">
  .new-offer
    fu-container(fluid)
      fu-row
        fu-col(xs12 sm6 md6 lg8)
          p Hello World
</template>
```
looks like ->
![image](https://cloud.githubusercontent.com/assets/1534503/22379318/defb4a00-e486-11e6-9334-925b33e87c56.png)

Same code looks like the following in separate `.pug` file:
![image](https://cloud.githubusercontent.com/assets/1534503/22379439/58a50c24-e487-11e6-9672-bf7de71d1767.png)

**VSCode version**: 1.8.1
**vscode-vue version**: 0.1.5
**OS**: OSX 10.11.6

**Comment by jakepeyser** [comment]
^ Ignore that comment, it seems `.vue` files are just not automatically recognized by VS Code. [This SO post](http://stackoverflow.com/questions/29956304/is-it-possible-to-associate-a-given-language-with-a-file-extention-in-vscode#answer-36790776) explains how to automate the usage of this syntax highlighter. Basically, you add the following to your `settings.json` file:

```json
"files.associations": {
    "*.vue": "vue"
}
```
